Update action.yml

diff --git a/.github/actions/action.yml b/.github/actions/action.yml
--- a/.github/actions/action.yml
+++ b/.github/actions/action.yml
@@ -883,13 +883,16 @@ runs:
         
         if [ "${{ env.OP_SUSFS }}" = true ]; then
           echo "Using SUSFS branch/commit: $SUSFS_BRANCH"
-          if ! retry_fetch_archive "https://gitlab.com/simonpunk/susfs4ksu.git" "$SUSFS_BRANCH"; then
-            echo "::error::Failed to fetch SUSFS archive after multiple attempts"
-            exit 1
-          fi
+          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "gki-android16-6.12"      
+          cd susfs4ksu
+          git fetch https://gitlab.com/simonpunk/susfs4ksu.git $SUSFS_BRANCH
+          # if ! retry_fetch_archive "https://gitlab.com/simonpunk/susfs4ksu.git" "$SUSFS_BRANCH"; then
+          #  echo "::error::Failed to fetch SUSFS archive after multiple attempts"
+          #  exit 1
+          # fi
           echo "SUSFS_COMMIT_SHA=$SUSFS_BRANCH" >> $GITHUB_ENV
         fi
-        cd ..
+        cd ../../
         echo "✅ Dependencies cloned"
         echo "::endgroup::"
 
